drivebot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  rightWheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: rightWheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  leftWheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: leftWheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
